
image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - dist/

Build:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
      - dist/

preview - staging:
  stage: deploy
  script:
    - npm install
    - npm run clean
    - npm run build
    - cp CNAME dist/
    - node_modules/.bin/surge dist
  except:
    - master

preview - production:
  only:
    - master
  stage: deploy
  script:
    - npm install
    - npm run clean
    - npm run build
    - cp DNAME dist/
    - node_modules/.bin/surge dist