
image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/
    - dist/

Build:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
      - dist/

Testing:
  image: cypress/base:10
  stage: test
  before_script:
    - npm run clean
    - npm install
    - npm install cypress --save
    - npm install start-server-and-test --save
    - npm install http-server --save
    - npm install @vue/cli
  script:
    - npm run test

preview - staging:
  stage: deploy
  script:
    - npm install
    - npm run clean
    - npm run build
    - cp CNAME dist/
    - node_modules/.bin/surge dist
  except:
    - master

preview - production:
  only:
    - master
  stage: deploy
  script:
    - npm install
    - npm run clean
    - npm run build
    - node_modules/.bin/surge dist hotelservice-production.surge.sh